---
- name: instalando servidor web no Debian
  package:
   name: apache2
   state: present
  when: ansible_os_family == "Debian"

- name: instalando servidor web no redhat
  package:
   name: httpd
   state: present
  when: ansible_os_family == "RedHat"
